name: PR Trigger

on:
  pull_request:
    types: [opened]

jobs:
  pr_trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Add your desired steps here
