name: Hello World from App1

on:
  workflow_call:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@4.2.2
        with:
           repository: ${{ github.repository }}
      - run: echo "👋 Hello from App1 Repo!"
