name: AWS CodeDeploy Deployment

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  workflow_dispatch:
    inputs:
      package_to_deploy:
        description: 'Path or content of the package to deploy'
        required: false  # Optional input as an environment variable will be used

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository's code

      - name: Set environment variable
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "PACKAGE_TO_DEPLOY=${{ github.event.inputs.package_to_deploy }}" >> $GITHUB_ENV

      - name: Create deployment package
        run: |
          echo "${{ env.PACKAGE_TO_DEPLOY }}" > deployment_package.txt
          cat deployment_package.txt  # Display the content of the deployment package for verification
